/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appLayoutRouteImport } from './routes/(app)/_layout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appLayoutSettingsRouteImport } from './routes/(app)/_layout/settings'
import { Route as appLayoutDashboardRouteImport } from './routes/(app)/_layout/dashboard'
import { Route as appLayoutJobsIndexRouteImport } from './routes/(app)/_layout/jobs/index'
import { Route as appLayoutClientsIndexRouteImport } from './routes/(app)/_layout/clients/index'
import { Route as appLayoutJobsJobIdRouteImport } from './routes/(app)/_layout/jobs/$jobId'
import { Route as appLayoutClientsClientIdRouteImport } from './routes/(app)/_layout/clients/$clientId'
import { Route as appLayoutClientsClientIdIndexRouteImport } from './routes/(app)/_layout/clients/$clientId/index'
import { Route as appLayoutClientsClientIdServiceAgreementsIndexRouteImport } from './routes/(app)/_layout/clients/$clientId/service-agreements/index'
import { Route as appLayoutClientsClientIdJobsIndexRouteImport } from './routes/(app)/_layout/clients/$clientId/jobs/index'
import { Route as appLayoutClientsClientIdInsuranceIndexRouteImport } from './routes/(app)/_layout/clients/$clientId/insurance/index'
import { Route as appLayoutClientsClientIdGoalsIndexRouteImport } from './routes/(app)/_layout/clients/$clientId/goals/index'
import { Route as appLayoutClientsClientIdFileNotesIndexRouteImport } from './routes/(app)/_layout/clients/$clientId/file-notes/index'
import { Route as appLayoutClientsClientIdDocumentsIndexRouteImport } from './routes/(app)/_layout/clients/$clientId/documents/index'
import { Route as appLayoutClientsClientIdCashflowIndexRouteImport } from './routes/(app)/_layout/clients/$clientId/cashflow/index'
import { Route as appLayoutClientsClientIdBalanceSheetIndexRouteImport } from './routes/(app)/_layout/clients/$clientId/balance-sheet/index'

const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutSettingsRoute = appLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutDashboardRoute = appLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutJobsIndexRoute = appLayoutJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutClientsIndexRoute = appLayoutClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutJobsJobIdRoute = appLayoutJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutClientsClientIdRoute =
  appLayoutClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutClientsClientIdIndexRoute =
  appLayoutClientsClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appLayoutClientsClientIdRoute,
  } as any)
const appLayoutClientsClientIdServiceAgreementsIndexRoute =
  appLayoutClientsClientIdServiceAgreementsIndexRouteImport.update({
    id: '/service-agreements/',
    path: '/service-agreements/',
    getParentRoute: () => appLayoutClientsClientIdRoute,
  } as any)
const appLayoutClientsClientIdJobsIndexRoute =
  appLayoutClientsClientIdJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => appLayoutClientsClientIdRoute,
  } as any)
const appLayoutClientsClientIdInsuranceIndexRoute =
  appLayoutClientsClientIdInsuranceIndexRouteImport.update({
    id: '/insurance/',
    path: '/insurance/',
    getParentRoute: () => appLayoutClientsClientIdRoute,
  } as any)
const appLayoutClientsClientIdGoalsIndexRoute =
  appLayoutClientsClientIdGoalsIndexRouteImport.update({
    id: '/goals/',
    path: '/goals/',
    getParentRoute: () => appLayoutClientsClientIdRoute,
  } as any)
const appLayoutClientsClientIdFileNotesIndexRoute =
  appLayoutClientsClientIdFileNotesIndexRouteImport.update({
    id: '/file-notes/',
    path: '/file-notes/',
    getParentRoute: () => appLayoutClientsClientIdRoute,
  } as any)
const appLayoutClientsClientIdDocumentsIndexRoute =
  appLayoutClientsClientIdDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => appLayoutClientsClientIdRoute,
  } as any)
const appLayoutClientsClientIdCashflowIndexRoute =
  appLayoutClientsClientIdCashflowIndexRouteImport.update({
    id: '/cashflow/',
    path: '/cashflow/',
    getParentRoute: () => appLayoutClientsClientIdRoute,
  } as any)
const appLayoutClientsClientIdBalanceSheetIndexRoute =
  appLayoutClientsClientIdBalanceSheetIndexRouteImport.update({
    id: '/balance-sheet/',
    path: '/balance-sheet/',
    getParentRoute: () => appLayoutClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard': typeof appLayoutDashboardRoute
  '/settings': typeof appLayoutSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/clients/$clientId': typeof appLayoutClientsClientIdRouteWithChildren
  '/jobs/$jobId': typeof appLayoutJobsJobIdRoute
  '/clients/': typeof appLayoutClientsIndexRoute
  '/jobs/': typeof appLayoutJobsIndexRoute
  '/clients/$clientId/': typeof appLayoutClientsClientIdIndexRoute
  '/clients/$clientId/balance-sheet/': typeof appLayoutClientsClientIdBalanceSheetIndexRoute
  '/clients/$clientId/cashflow/': typeof appLayoutClientsClientIdCashflowIndexRoute
  '/clients/$clientId/documents/': typeof appLayoutClientsClientIdDocumentsIndexRoute
  '/clients/$clientId/file-notes/': typeof appLayoutClientsClientIdFileNotesIndexRoute
  '/clients/$clientId/goals/': typeof appLayoutClientsClientIdGoalsIndexRoute
  '/clients/$clientId/insurance/': typeof appLayoutClientsClientIdInsuranceIndexRoute
  '/clients/$clientId/jobs/': typeof appLayoutClientsClientIdJobsIndexRoute
  '/clients/$clientId/service-agreements/': typeof appLayoutClientsClientIdServiceAgreementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard': typeof appLayoutDashboardRoute
  '/settings': typeof appLayoutSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/jobs/$jobId': typeof appLayoutJobsJobIdRoute
  '/clients': typeof appLayoutClientsIndexRoute
  '/jobs': typeof appLayoutJobsIndexRoute
  '/clients/$clientId': typeof appLayoutClientsClientIdIndexRoute
  '/clients/$clientId/balance-sheet': typeof appLayoutClientsClientIdBalanceSheetIndexRoute
  '/clients/$clientId/cashflow': typeof appLayoutClientsClientIdCashflowIndexRoute
  '/clients/$clientId/documents': typeof appLayoutClientsClientIdDocumentsIndexRoute
  '/clients/$clientId/file-notes': typeof appLayoutClientsClientIdFileNotesIndexRoute
  '/clients/$clientId/goals': typeof appLayoutClientsClientIdGoalsIndexRoute
  '/clients/$clientId/insurance': typeof appLayoutClientsClientIdInsuranceIndexRoute
  '/clients/$clientId/jobs': typeof appLayoutClientsClientIdJobsIndexRoute
  '/clients/$clientId/service-agreements': typeof appLayoutClientsClientIdServiceAgreementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/(app)/_layout': typeof appLayoutRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(app)/_layout/dashboard': typeof appLayoutDashboardRoute
  '/(app)/_layout/settings': typeof appLayoutSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/_layout/clients/$clientId': typeof appLayoutClientsClientIdRouteWithChildren
  '/(app)/_layout/jobs/$jobId': typeof appLayoutJobsJobIdRoute
  '/(app)/_layout/clients/': typeof appLayoutClientsIndexRoute
  '/(app)/_layout/jobs/': typeof appLayoutJobsIndexRoute
  '/(app)/_layout/clients/$clientId/': typeof appLayoutClientsClientIdIndexRoute
  '/(app)/_layout/clients/$clientId/balance-sheet/': typeof appLayoutClientsClientIdBalanceSheetIndexRoute
  '/(app)/_layout/clients/$clientId/cashflow/': typeof appLayoutClientsClientIdCashflowIndexRoute
  '/(app)/_layout/clients/$clientId/documents/': typeof appLayoutClientsClientIdDocumentsIndexRoute
  '/(app)/_layout/clients/$clientId/file-notes/': typeof appLayoutClientsClientIdFileNotesIndexRoute
  '/(app)/_layout/clients/$clientId/goals/': typeof appLayoutClientsClientIdGoalsIndexRoute
  '/(app)/_layout/clients/$clientId/insurance/': typeof appLayoutClientsClientIdInsuranceIndexRoute
  '/(app)/_layout/clients/$clientId/jobs/': typeof appLayoutClientsClientIdJobsIndexRoute
  '/(app)/_layout/clients/$clientId/service-agreements/': typeof appLayoutClientsClientIdServiceAgreementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/settings'
    | '/api/auth/$'
    | '/clients/$clientId'
    | '/jobs/$jobId'
    | '/clients/'
    | '/jobs/'
    | '/clients/$clientId/'
    | '/clients/$clientId/balance-sheet/'
    | '/clients/$clientId/cashflow/'
    | '/clients/$clientId/documents/'
    | '/clients/$clientId/file-notes/'
    | '/clients/$clientId/goals/'
    | '/clients/$clientId/insurance/'
    | '/clients/$clientId/jobs/'
    | '/clients/$clientId/service-agreements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/settings'
    | '/api/auth/$'
    | '/jobs/$jobId'
    | '/clients'
    | '/jobs'
    | '/clients/$clientId'
    | '/clients/$clientId/balance-sheet'
    | '/clients/$clientId/cashflow'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/file-notes'
    | '/clients/$clientId/goals'
    | '/clients/$clientId/insurance'
    | '/clients/$clientId/jobs'
    | '/clients/$clientId/service-agreements'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/(app)/_layout'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(app)/_layout/dashboard'
    | '/(app)/_layout/settings'
    | '/api/auth/$'
    | '/(app)/_layout/clients/$clientId'
    | '/(app)/_layout/jobs/$jobId'
    | '/(app)/_layout/clients/'
    | '/(app)/_layout/jobs/'
    | '/(app)/_layout/clients/$clientId/'
    | '/(app)/_layout/clients/$clientId/balance-sheet/'
    | '/(app)/_layout/clients/$clientId/cashflow/'
    | '/(app)/_layout/clients/$clientId/documents/'
    | '/(app)/_layout/clients/$clientId/file-notes/'
    | '/(app)/_layout/clients/$clientId/goals/'
    | '/(app)/_layout/clients/$clientId/insurance/'
    | '/(app)/_layout/clients/$clientId/jobs/'
    | '/(app)/_layout/clients/$clientId/service-agreements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  appLayoutRoute: typeof appLayoutRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/settings': {
      id: '/(app)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appLayoutSettingsRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/dashboard': {
      id: '/(app)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appLayoutDashboardRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/jobs/': {
      id: '/(app)/_layout/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof appLayoutJobsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/clients/': {
      id: '/(app)/_layout/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof appLayoutClientsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/jobs/$jobId': {
      id: '/(app)/_layout/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof appLayoutJobsJobIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/clients/$clientId': {
      id: '/(app)/_layout/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof appLayoutClientsClientIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/clients/$clientId/': {
      id: '/(app)/_layout/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof appLayoutClientsClientIdIndexRouteImport
      parentRoute: typeof appLayoutClientsClientIdRoute
    }
    '/(app)/_layout/clients/$clientId/service-agreements/': {
      id: '/(app)/_layout/clients/$clientId/service-agreements/'
      path: '/service-agreements'
      fullPath: '/clients/$clientId/service-agreements/'
      preLoaderRoute: typeof appLayoutClientsClientIdServiceAgreementsIndexRouteImport
      parentRoute: typeof appLayoutClientsClientIdRoute
    }
    '/(app)/_layout/clients/$clientId/jobs/': {
      id: '/(app)/_layout/clients/$clientId/jobs/'
      path: '/jobs'
      fullPath: '/clients/$clientId/jobs/'
      preLoaderRoute: typeof appLayoutClientsClientIdJobsIndexRouteImport
      parentRoute: typeof appLayoutClientsClientIdRoute
    }
    '/(app)/_layout/clients/$clientId/insurance/': {
      id: '/(app)/_layout/clients/$clientId/insurance/'
      path: '/insurance'
      fullPath: '/clients/$clientId/insurance/'
      preLoaderRoute: typeof appLayoutClientsClientIdInsuranceIndexRouteImport
      parentRoute: typeof appLayoutClientsClientIdRoute
    }
    '/(app)/_layout/clients/$clientId/goals/': {
      id: '/(app)/_layout/clients/$clientId/goals/'
      path: '/goals'
      fullPath: '/clients/$clientId/goals/'
      preLoaderRoute: typeof appLayoutClientsClientIdGoalsIndexRouteImport
      parentRoute: typeof appLayoutClientsClientIdRoute
    }
    '/(app)/_layout/clients/$clientId/file-notes/': {
      id: '/(app)/_layout/clients/$clientId/file-notes/'
      path: '/file-notes'
      fullPath: '/clients/$clientId/file-notes/'
      preLoaderRoute: typeof appLayoutClientsClientIdFileNotesIndexRouteImport
      parentRoute: typeof appLayoutClientsClientIdRoute
    }
    '/(app)/_layout/clients/$clientId/documents/': {
      id: '/(app)/_layout/clients/$clientId/documents/'
      path: '/documents'
      fullPath: '/clients/$clientId/documents/'
      preLoaderRoute: typeof appLayoutClientsClientIdDocumentsIndexRouteImport
      parentRoute: typeof appLayoutClientsClientIdRoute
    }
    '/(app)/_layout/clients/$clientId/cashflow/': {
      id: '/(app)/_layout/clients/$clientId/cashflow/'
      path: '/cashflow'
      fullPath: '/clients/$clientId/cashflow/'
      preLoaderRoute: typeof appLayoutClientsClientIdCashflowIndexRouteImport
      parentRoute: typeof appLayoutClientsClientIdRoute
    }
    '/(app)/_layout/clients/$clientId/balance-sheet/': {
      id: '/(app)/_layout/clients/$clientId/balance-sheet/'
      path: '/balance-sheet'
      fullPath: '/clients/$clientId/balance-sheet/'
      preLoaderRoute: typeof appLayoutClientsClientIdBalanceSheetIndexRouteImport
      parentRoute: typeof appLayoutClientsClientIdRoute
    }
  }
}

interface appLayoutClientsClientIdRouteChildren {
  appLayoutClientsClientIdIndexRoute: typeof appLayoutClientsClientIdIndexRoute
  appLayoutClientsClientIdBalanceSheetIndexRoute: typeof appLayoutClientsClientIdBalanceSheetIndexRoute
  appLayoutClientsClientIdCashflowIndexRoute: typeof appLayoutClientsClientIdCashflowIndexRoute
  appLayoutClientsClientIdDocumentsIndexRoute: typeof appLayoutClientsClientIdDocumentsIndexRoute
  appLayoutClientsClientIdFileNotesIndexRoute: typeof appLayoutClientsClientIdFileNotesIndexRoute
  appLayoutClientsClientIdGoalsIndexRoute: typeof appLayoutClientsClientIdGoalsIndexRoute
  appLayoutClientsClientIdInsuranceIndexRoute: typeof appLayoutClientsClientIdInsuranceIndexRoute
  appLayoutClientsClientIdJobsIndexRoute: typeof appLayoutClientsClientIdJobsIndexRoute
  appLayoutClientsClientIdServiceAgreementsIndexRoute: typeof appLayoutClientsClientIdServiceAgreementsIndexRoute
}

const appLayoutClientsClientIdRouteChildren: appLayoutClientsClientIdRouteChildren =
  {
    appLayoutClientsClientIdIndexRoute: appLayoutClientsClientIdIndexRoute,
    appLayoutClientsClientIdBalanceSheetIndexRoute:
      appLayoutClientsClientIdBalanceSheetIndexRoute,
    appLayoutClientsClientIdCashflowIndexRoute:
      appLayoutClientsClientIdCashflowIndexRoute,
    appLayoutClientsClientIdDocumentsIndexRoute:
      appLayoutClientsClientIdDocumentsIndexRoute,
    appLayoutClientsClientIdFileNotesIndexRoute:
      appLayoutClientsClientIdFileNotesIndexRoute,
    appLayoutClientsClientIdGoalsIndexRoute:
      appLayoutClientsClientIdGoalsIndexRoute,
    appLayoutClientsClientIdInsuranceIndexRoute:
      appLayoutClientsClientIdInsuranceIndexRoute,
    appLayoutClientsClientIdJobsIndexRoute:
      appLayoutClientsClientIdJobsIndexRoute,
    appLayoutClientsClientIdServiceAgreementsIndexRoute:
      appLayoutClientsClientIdServiceAgreementsIndexRoute,
  }

const appLayoutClientsClientIdRouteWithChildren =
  appLayoutClientsClientIdRoute._addFileChildren(
    appLayoutClientsClientIdRouteChildren,
  )

interface appLayoutRouteChildren {
  appLayoutDashboardRoute: typeof appLayoutDashboardRoute
  appLayoutSettingsRoute: typeof appLayoutSettingsRoute
  appLayoutClientsClientIdRoute: typeof appLayoutClientsClientIdRouteWithChildren
  appLayoutJobsJobIdRoute: typeof appLayoutJobsJobIdRoute
  appLayoutClientsIndexRoute: typeof appLayoutClientsIndexRoute
  appLayoutJobsIndexRoute: typeof appLayoutJobsIndexRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appLayoutDashboardRoute: appLayoutDashboardRoute,
  appLayoutSettingsRoute: appLayoutSettingsRoute,
  appLayoutClientsClientIdRoute: appLayoutClientsClientIdRouteWithChildren,
  appLayoutJobsJobIdRoute: appLayoutJobsJobIdRoute,
  appLayoutClientsIndexRoute: appLayoutClientsIndexRoute,
  appLayoutJobsIndexRoute: appLayoutJobsIndexRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  appLayoutRoute: appLayoutRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
